name: Trend
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: 0.10.9
  assets_audio_player: 2.0.8+3 
  flutter_auth_buttons: ^0.8.0
  google_sign_in:
  keyboard_avoider: ^0.1.2
  http: ^0.12.2
  provider: ^4.3.2+1
  custom_switch: ^0.0.1
  animations: ^1.1.2
  flutter_radio: ^0.1.8
  get: ^3.10.1
  timer_builder: ^1.3.0
  splashscreen: ^1.2.0
  cupertino_icons: ^0.1.3
  flutter_webview_plugin: ^0.3.10+1
  firebase_auth: 
  firebase_core: 
  firebase_database:
  cloud_firestore:
  lottie: ^0.6.0
  animated_splash_screen: ^1.0.1+2
  get_storage: ^1.3.1
  webview_flutter: ^1.0.1
  flutter_spinkit: ^4.1.2
  connectivity: ^0.4.9+5
  cached_network_image:
  webview_flutter_plus: ^0.1.1+9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/videos/login_video_animation.mp4
    - assets/images/dj_features.jpg
    - assets/images/online_tv.jpg
    - assets/images/tv.png
    - assets/images/live.png
    - assets/images/splash.png
    - assets/logo/trend_logo.png
    - assets/logo/logo_white.png
    - assets/images/facebook.png
    - assets/images/play_cover.png
    - assets/images/google.png
    - assets/json/Trend-Splash-Animation.json
    - assets/terms/termsofuse.txt

  fonts:
      - family: Sofia_regular
        fonts:
          - asset: assets/fonts/sofia_regular.ttf
      - family: Sofia_bold
        fonts:
        - asset: assets/fonts/sofia_bold.ttf
      - family:  TrendIcons   
        fonts:
          - asset: assets/fonts/TrendIcons.ttf

  # adaptive_icon_background: “lib/assets/launcher/background.png”
  # adaptive_icon_foreground: “lib/assets/launcher/foreground.png”
  # To add assets to your application, add an assets section, like this:
  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
